### ISSUE TITLE
[epic] What's the situation and what can we do about it?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/climate#22]
This is the overall epic for the whole project.

## Tasks

*.[ ] Do an SCQH to identify what question we are trying to answer
  * [ ] SCQ(H)
  * [ ] Issue tree
* [ ] Key materials
  * [ ] Identify key materials to read / process
  * [ ] Acquire them
  * [ ] Read them
  * [ ] Summarize them
* [ ] Utilize them to address issue tree
* [ ] Come up with hypothesis (or hypotheses)

## Inbox

* [ ] Key figures (mainly from without hot air) in one place
* Energy budgets for different countries
