### ISSUE TITLE
Website v1: basic website publishing current markdown content

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/climate#4]
Current just markdown in git repo. Would like to publish this properly plus we need that for better rendering etc.

Suggested url: climate.lifeitself.us

## Acceptance

* [x] Site is live at climate.lifeitself.us
* [x] Auto-publishes all markdown starting from root directory and ignoring "site" directory

## Tasks

* [x] Basic next.js site based on the markdown
  * [x] check if templates out there we can use **Checked. https://github.com/timlrx/tailwind-nextjs-starter-blog looks good but over-complex for our needs. Let's start from scratch (and our existing efforts)**
  * [x] Install skeleton with tailwind
  * [x] Add Markdown/MDX support
  * [x] Implement catch-all routing
* [x] Deploy
  * [x] choose between vercel or github pages **DONE: github pages (no paid plan needed)**
  * [x] work out how to do on github pages
  * [x] implement that
* [x] DNS

**Comment by rufuspollock** [comment]
FIXED.
