### ISSUE TITLE
David MacKay's Sustainable Energy without the Hot Air: markdown-ed, integrated

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/climate#5]
Integrate and make annotatable David MacKay's *Sustainable Energy - Without the Hot Air* (http://withouthotair.com).

## Context

David MacKay's *Sustainable Energy - Without the Hot Air* (http://withouthotair.com) was a landmark text and still provides an incredible foundation for looking at energy policy and climate change. 

However, the book was published in 2008. As David tragically passed away in 2016 the book did not get to updated and is now, as of 2020, becoming a little out of date. See this 2017 article on Carbon Commentary with concrete suggestions https://www.carboncommentary.com/blog/2017/3/30/l6qcqgoedse1wmjjz87t09usoq6jva and associated thread on ycombinator: https://news.ycombinator.com/item?id=14009057

We are therefore thinking of getting a source markdown version and published copy here for 3 reasons:

* A local text we can integrate and reference
* Collaborative updating of the text (as per above)
* An updated web publication of the text: similarly to the previous point the existing web version of the text could benefit from a more up to date presentation.

## Tasks

* [x] Decide whether to keep in separate repo or merge to climate repo **Merge to climate repo as let's keep things simple**
* [x] Identify source version of the book (e.g. epub or tex or html) **DONE. Went for the epub. Tito Jankowski has a version here https://github.com/titojankowski/sustainable_energy_without_the_hot_air but its from html as not so great quality**
* [x] Create sub-project in this repo for it
  * [x] Archive raw source material
  * [x] Create README etc
* [x] convert that to markdown **See https://github.com/life-itself/climate/tree/main/sewtha**
  * [x] pandoc to get raw source **See the `extract.sh`**
  * [x] clean that **See the `extract.sh`**
  * [x] split into sections (or keep as one) **Keep as one**
* [x] Split into sections - this is needed I think **DONE: 24 Aug. Started again with epub. See extract.py**
* [x] home page for it e.g. at /without-hot-air/  
  * [x] remove first effort at /sewtha/ and add redirect 
* [x] publish **DONE: Live for now at https://climate.lifeitself.us/sewtha/README**

Misc

* [x] shut down https://github.com/life-itself/without-the-hot-air and move issues over

### Sources

* Epub
* Tex version (original source) is here: http://www.inference.org.uk/sustainable/book/tex/ Though note that:

   > It looks like that is the actual working directory and some files were not saved properly. The #BushOnGrass.tex# files with # at the start and end are backups made by Emacs, and usually deleted when the file is saved correctly.
  
  * Data directory: http://www.inference.org.uk/sustainable/book/data/

### License

Original text is copyright Professor David JC MacKay FRS (Professor of Natural Philosophy, Department of Physics, University of Cambridge) and licensed under a Creative Commons Attribution-Non-Commercial-Share-Alike 2.0 UK: England & Wales Licence. See http://withouthotair.com/about.html

> This is a free book. I didn't write this book to make money. I wrote it because sustainable energy is important. If you would like to have the book for free for your own use, please help yourself to any of the electronic versions on this website. There's pdf and html versions (thanks to William Sigmund!); we are working on other formats.
>
> This is a free book in a second sense: you are free to use all the material in this book, except for the cartoons and the photos with a named photographer, under the Creative Commons Attribution-Non-Commercial-Share-Alike 2.0 UK: England & Wales Licence. (The cartoons and photos are excepted because the authors have generally given me permission only to include their work, not to share it under a Creative Commons license.) You are especially welcome to use my materials for educational purposes. This website includes links to separate high-quality files for each of the figures in the book.

Additions and modifications by other authors are dual-licensed under a Creative Commons Attribution License v4 (unported) and Creative Commons Attribution-Non-Commercial-Share-Alike 2.0 UK (as required by the Share-Alike license).

**Comment by rufuspollock** [comment]
FIXED. All done. Follow up in #6 and #16  and #21
