### ISSUE TITLE
Content organization v0.2 (from github repo as presentation to source for website) 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/climate#7]
When starting this repo we took the KISS and started with the README as main content and github itself as publication platform.

With recent updates (Aug 2021) to have a proper website (see e.g. #4) we want to refactor a bit.

Layout

```
README.md  # intro to this repo (not published)
content/          # main content folder - files in here are direct published
   notes/              # random notes zettelkasten style, published largely as blog
sewtha/           # special folder for sustainable energy without the hot air
site/                  # website app
```

## Tasks

* [x] Decide on structure **DONE. See above**
* [x] Refactor into above structure
* [x] Add in root README which is more developer oriented (now original README has moved to home)
* [x] Integrate updated climate overview I have been working on (in data literate) into the new home.md (old README)
* [x] Fix up website to load content from new location

**Comment by rufuspollock** [comment]
FIXED. All done.
